### ISSUE TITLE
sflix is not working

### ISSUE THREAD

**Issue by madrid2022ok** [stantanasi/streamflix#10] opened 2022-12-01 00:52 UTC
![A14B56A1-2040-42E8-8AF9-1630AF9252AF](https://user-images.githubusercontent.com/105641464/204939454-6782fe92-4d48-44c1-984b-962f3209119b.jpeg)

It happens to me in the series and movies on android tv I get this error

**Comment by stantanasi** [comment] 2022-12-01 20:24
> ![A14B56A1-2040-42E8-8AF9-1630AF9252AF](https://user-images.githubusercontent.com/105641464/204939454-6782fe92-4d48-44c1-984b-962f3209119b.jpeg)
> 
> It happens to me in the series and movies on android tv I get this error

Duplicate of #5

**Comment by stantanasi** [comment] 2022-12-01 20:26
> and in the search engine I click and I can't search I can't write the name of the movies and series sflix

Can you provide more details.
Did the keyboard show ? What devices are you using with which Android version ?

**Comment by madrid2022ok** [comment] 2022-12-01 23:46
![IMG-20220127-WA0036](https://user-images.githubusercontent.com/105641464/205182310-8698a888-e096-47c4-be9d-df04bff3a03e.jpg)

the detail is that I have this android tv comes with control

I put search with that control I can't write that's the detail friend

**Comment by madrid2022ok** [comment] 2022-12-01 23:49
![16699384203133938853061028254156](https://user-images.githubusercontent.com/105641464/205182782-e62ebdf7-f3e0-4a79-a874-844aabbde5cd.jpg)
that's the detail
I have android tv with the control that came to me and that was just the beelink keyboard detail

**Comment by stantanasi** [comment] 2022-12-02 12:46
I don't understand the issue you are having. So that I can solve it, could you give me the steps to reproduce your bug?

Did you manage to select the _Search movies, TV shows_ input? 
Did the Android keyboard show up? 
Can you type your query and hit enter? 
Did the app load movies and TV shows based on your query? 
And can you select a movie or TV show after searching?

![image](https://user-images.githubusercontent.com/46174829/205281783-fcbc450e-06eb-49a5-bf8c-25c6d93fb40e.png)

**Comment by madrid2022ok** [comment] 2022-12-02 14:03
![20221202_150027](https://user-images.githubusercontent.com/105641464/205310071-7c6e153f-0768-4239-805a-bf469724f087.jpg)


the episodes do not come out and also the movies remain black with sflix provider

**Comment by stantanasi** [comment] 2022-12-02 14:50
When episodes do not come out, which TV show did you select?
Could you explain precisely the steps I need to follow to reproduce your bug?

**Comment by madrid2022ok** [comment] 2022-12-02 14:57
in the planet sheen serie the episodes don't come out in sflix  that's why they don't come out in the other series and movies

**Comment by stantanasi** [comment] 2022-12-02 15:09
> in the planet sheen serie the episodes don't come out in sflix that's why they don't come out in the other series and movies

If episodes or movies are not available on providers, there is nothing I can do about it.

_My app does not host any content on the app, and has no control over what media is put up or taken down. The app functions like any other search engine, such as Google. The app does not host, upload or manage any videos, films or content. It simply crawls, aggregates and displayes links in a convenient, user-friendly interface._

**Comment by madrid2022ok** [comment] 2022-12-02 15:52
There will be an updates and improvements for the sflix app and more providers pages for the sflix app

**Comment by madrid2022ok** [comment] 2022-12-02 21:18
hello

**Comment by madrid2022ok** [comment] 2022-12-02 21:55
![172A16E2-BF96-4C85-B186-72D7659002F6](https://user-images.githubusercontent.com/105641464/205396717-1964e665-c723-4654-bbbf-1389df87328f.jpeg)

It does not load the movies and series I know there is and it does not come out more Movies and series

**Comment by madrid2022ok** [comment] 2022-12-03 11:07
Hello friend

**Comment by stantanasi** [comment] 2022-12-03 11:37
> It does not load the movies and series I know there is and it does not come out more Movies and series

My application only loads the first page of providers. For now, it's not possible to load the second, third... pages.

![image](https://user-images.githubusercontent.com/46174829/205439013-d5646dfc-dbf7-4a5e-a729-fba308e3a9f2.png)

**Comment by HeyPapito** [comment] 2022-12-08 10:43
Yes I also get the same error for some shows. Able to watch the new "Wednesday" tv show but get the same openssl bad decrypt error when trying to watch "Never have I ever" tv show

**Comment by stantanasi** [comment] 2022-12-08 18:24
> Yes I also get the same error for some shows. Able to watch the new "Wednesday" tv show but get the same openssl bad decrypt error when trying to watch "Never have I ever" tv show

Duplicate of #5

**Closed** 2023-06-01 18:52 UTC
