### ISSUE TITLE
Sflix is not working

### ISSUE THREAD

**Issue by cristianoashok** [stantanasi/streamflix#64] opened 2024-01-21 09:23 UTC
### Description

In the choose a provider, when I click SFlix it shows "connection reset" and keeps loading. And for anymovie, when I click watch now on movies it shows "no extractor found" and stays in the player and when I click on the setting icon in the player and click on the server, there is no server listed in it. Aniwatch works fine.

### Reproduction steps

.

### App version

1.4.0

### Operating system

Android 11

### Logs

```bash
.
```

### Please confirm the following

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by Imnoteric** [comment] 2024-02-01 03:15
The app was working for me at first then it stopped loading movies about 2 or so days ago.

**Comment by JimmyJichi** [comment] 2024-02-17 20:38
Having the same issue on my Chromecast.  Weirdly it works fine on the emulator.

<details>
<summary>Log</summary>

`    {
      "header": {
        "logLevel": "WARN",
        "pid": 14548,
        "tid": 14548,
        "applicationId": "com.tanasi.streamflix.debug",
        "processName": "com.tanasi.streamflix.debug",
        "tag": "Glide",
        "timestamp": {
          "seconds": 1708201455,
          "nanos": 705000000
        }
      },
      "message": "Load failed for https://img.sflix.to/xxrz/400x400/100/66/35/66356c25ce98cb12993249e21742b129/66356c25ce98cb12993249e21742b129.png with size [228x228]\nclass com.bumptech.glide.load.engine.GlideException: Failed to load resource\nThere was 1 root cause:\ncom.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)\n call GlideException#logRootCauses(String) for more detail\n  Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE\nThere was 1 root cause:\ncom.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)\n call GlideException#logRootCauses(String) for more detail\n    Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed\nThere was 1 root cause:\ncom.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)\n call GlideException#logRootCauses(String) for more detail\n      Cause (1 of 1): class com.bumptech.glide.load.HttpException: Failed to connect or obtain data, status code: -1"
    },
    {
      "header": {
        "logLevel": "INFO",
        "pid": 14548,
        "tid": 14548,
        "applicationId": "com.tanasi.streamflix.debug",
        "processName": "com.tanasi.streamflix.debug",
        "tag": "Glide",
        "timestamp": {
          "seconds": 1708201455,
          "nanos": 714000000
        }
      },
      "message": "Root cause (1 of 1)\ncom.bumptech.glide.load.HttpException: Failed to connect or obtain data, status code: -1\n\tat com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:98)\n\tat com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:58)\n\tat com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)\n\tat com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)\n\tat com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)\n\tat com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)\n\tat com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)\n\tat com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)\n\tat java.lang.Thread.run(Thread.java:920)\n\tat com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:372)\nCaused by: java.net.SocketException: Connection reset\n\tat java.net.SocketInputStream.read(SocketInputStream.java:215)\n\tat java.net.SocketInputStream.read(SocketInputStream.java:144)\n\tat com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)\n\tat com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)\n\tat com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)\n\tat com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)\n\tat com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)\n\tat com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)\n\tat com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)\n\tat com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)\n\tat com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)\n\tat com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)\n\tat com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)\n\tat com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)\n\tat com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)\n\tat com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)\n\tat com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)\n\tat com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)\n\tat com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)\n\tat com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:93)\n\tat com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:58) \n\tat com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100) \n\tat com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95) \n\tat com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88) \n\tat com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311) \n\tat com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280) \n\tat com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235) \n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) \n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) \n\tat com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413) \n\tat java.lang.Thread.run(Thread.java:920) \n\tat com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:372) "
    }`
</details>

**Comment by dev-sharma-deltatre** [comment] 2024-02-21 10:39
Same here. App not loading.

**Comment by RayzaEFC** [comment] 2024-02-23 16:00
The SfLix provider still not loading in app version 1.5.0. The app has potential but I think maybe a better provider/website needs to be used to pull links as this has been a constant issue regarding the app

**Comment by stantanasi** [comment] 2024-02-23 21:47
Okay, so for me, the SFlix provider works fine on both my Chromecast and emulator. I can load all pages and navigate through the app without issues.
As for resolving your error, I'm not sure how to fix it since I haven't encountered it myself. However, you could try clearing the cache and/or data of the app, or even reinstalling it. Another option is to check if you can access the [SFlix website](https://sflix.to/home) on your computer to determine if the issue is not caused by your internet connection, DNS, etc.

Also, I'm aware that occasionally there may be errors when trying to watch a show (such as `bad base64` or `bad decrypt`). Unfortunately, these errors are beyond my control as they are related to changes made by the video host service to their encryption methods.

**Comment by RayzaEFC** [comment] 2024-02-23 22:06
So I have tested further and it seems if I use a VPN then it will work so ISP must be blocking. Also testing the site/provider https://sflix.to/home on my laptop it also isn't loading (ISP block at a guess) but https://sflixz.to/home does work. Although it's not a true clone site. I do have loads of clone websites of the provider you use that do work if you want me to send them or direct6 you to them? One of them being https://dopebox.to/home

**Comment by Shotay-17** [comment] 2024-08-02 07:04
Firstly , Check if the Servers are down or there is any Outages .[ [Sflix.com](https://techthanos.com/sflix/)]([url]usually dont work for me and when i check the sites -the community says that the site  is down .Use a VPN or just move on other alternative sites .

**Comment by stantanasi** [comment] 2024-10-14 17:39
Closing this issue because I can't do anything about that (except adding a SFlix clone, but it will takes time before I do that)

**Closed by stantanasi** 2024-10-14 17:39 UTC
Labels: bug
