### ISSUE TITLE
My install is prompting no extractors found error when playing any file

### ISSUE THREAD

**Issue by 1gby** [stantanasi/streamflix#204] opened 2024-10-24 17:44 UTC
### Description

My install is prompting no extractors found error when playing any file

### Provider

Sflix main provider 

### Reproduction steps

My install is prompting no extractors found error when playing any file using sflix provider.. Tmdb seems to work.. this has been the last like 10 updates for me 

### Operating system

Chrome cast with google tv 

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by 1gby** [comment] 2024-10-24 18:34
After a fresh install it's still the same but upcloud shows a 404 errors on some streams but still won't play

**Comment by stantanasi** [comment] 2024-10-24 19:52
Duplicate of #181

**Comment by stantanasi** [comment] 2024-10-24 19:53
I recommend you to use an other provider for now

**Closed by stantanasi** 2024-10-24 19:52 UTC
Labels: bug
